-- GlowStock: PostgreSQL schema for Supabase
-- Four entities: supplier, produk, transaksi, detail_transaksi

create table public.supplier (
    supplier_id bigint generated by default as identity primary key,
    nama_supplier varchar(100) not null,
    no_telepon varchar(20),
    alamat text,
    created_at timestamptz not null default now()
);

create table public.produk (
    produk_id bigint generated by default as identity primary key,
    kode_produk varchar(20) not null unique,
    nama_produk varchar(100) not null,
    kategori varchar(50) not null,
    harga_beli numeric(15, 2) not null default 0 check (harga_beli >= 0),
    harga_jual numeric(15, 2) not null default 0 check (harga_jual >= 0),
    stok integer not null default 0 check (stok >= 0),
    stok_minimum integer not null default 5 check (stok_minimum >= 0),
    satuan varchar(20) not null default 'pcs',
    created_at timestamptz not null default now()
);

create table public.transaksi (
    transaksi_id bigint generated by default as identity primary key,
    nomor_transaksi varchar(40) not null unique,
    tanggal date not null default current_date,
    tipe_transaksi varchar(10) not null check (tipe_transaksi in ('MASUK', 'KELUAR')),
    supplier_id bigint references public.supplier(supplier_id) on delete set null,
    keterangan text,
    total numeric(15, 2) not null default 0 check (total >= 0),
    created_at timestamptz not null default now()
);

create table public.detail_transaksi (
    detail_id bigint generated by default as identity primary key,
    transaksi_id bigint not null references public.transaksi(transaksi_id) on delete cascade,
    produk_id bigint not null references public.produk(produk_id) on delete restrict,
    jumlah integer not null check (jumlah > 0),
    harga numeric(15, 2) not null check (harga >= 0),
    subtotal numeric(15, 2) generated always as (jumlah * harga) stored
);

create index transaksi_tanggal_idx on public.transaksi (tanggal desc);
create index detail_transaksi_transaksi_id_idx on public.detail_transaksi (transaksi_id);
create index detail_transaksi_produk_id_idx on public.detail_transaksi (produk_id);

create or replace view public.view_laporan_transaksi
with (security_invoker = true)
as
select
    t.transaksi_id,
    t.nomor_transaksi,
    t.tanggal,
    t.tipe_transaksi,
    t.keterangan,
    t.total,
    s.nama_supplier
from public.transaksi as t
left join public.supplier as s on s.supplier_id = t.supplier_id;

create or replace view public.view_nilai_persediaan
with (security_invoker = true)
as
select
    produk_id,
    kode_produk,
    nama_produk,
    kategori,
    stok,
    harga_beli,
    stok * harga_beli as nilai_persediaan
from public.produk;

create or replace function public.proses_transaksi(
    p_tipe text,
    p_supplier_id bigint,
    p_keterangan text,
    p_items jsonb
)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
    v_tipe text := upper(coalesce(p_tipe, ''));
    v_transaksi_id bigint;
    v_nomor_transaksi text;
    v_item jsonb;
    v_produk_id bigint;
    v_jumlah integer;
    v_harga numeric(15, 2);
    v_stok integer;
    v_total numeric(15, 2) := 0;
begin
    if v_tipe not in ('MASUK', 'KELUAR') then
        raise exception 'Tipe transaksi harus MASUK atau KELUAR.';
    end if;

    if jsonb_typeof(p_items) is distinct from 'array' then
        raise exception 'Detail transaksi harus berbentuk array.';
    end if;

    if jsonb_array_length(p_items) = 0 then
        raise exception 'Transaksi harus memiliki minimal satu produk.';
    end if;

    v_nomor_transaksi := 'TRX-' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS')
        || '-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 6);

    insert into public.transaksi (
        nomor_transaksi,
        tipe_transaksi,
        supplier_id,
        keterangan
    ) values (
        v_nomor_transaksi,
        v_tipe,
        p_supplier_id,
        nullif(trim(coalesce(p_keterangan, '')), '')
    )
    returning transaksi_id into v_transaksi_id;

    for v_item in select value from jsonb_array_elements(p_items)
    loop
        begin
            v_produk_id := (v_item ->> 'produk_id')::bigint;
            v_jumlah := (v_item ->> 'jumlah')::integer;
            v_harga := (v_item ->> 'harga')::numeric(15, 2);
        exception
            when invalid_text_representation or numeric_value_out_of_range then
                raise exception 'Detail transaksi tidak valid.';
        end;

        if v_produk_id is null or v_jumlah is null or v_jumlah <= 0
           or v_harga is null or v_harga < 0 then
            raise exception 'Produk, jumlah, atau harga transaksi tidak valid.';
        end if;

        select stok into v_stok
        from public.produk
        where produk_id = v_produk_id
        for update;

        if not found then
            raise exception 'Produk dengan ID % tidak ditemukan.', v_produk_id;
        end if;

        if v_tipe = 'KELUAR' and v_jumlah > v_stok then
            raise exception 'Stok produk ID % tidak mencukupi.', v_produk_id;
        end if;

        update public.produk
        set stok = case
            when v_tipe = 'MASUK' then stok + v_jumlah
            else stok - v_jumlah
        end
        where produk_id = v_produk_id;

        insert into public.detail_transaksi (
            transaksi_id,
            produk_id,
            jumlah,
            harga
        ) values (
            v_transaksi_id,
            v_produk_id,
            v_jumlah,
            v_harga
        );

        v_total := v_total + (v_jumlah * v_harga);
    end loop;

    update public.transaksi
    set total = v_total
    where transaksi_id = v_transaksi_id;

    return jsonb_build_object(
        'transaksi_id', v_transaksi_id,
        'nomor_transaksi', v_nomor_transaksi
    );
end;
$$;

-- Demo mode: app data is publicly accessible through the publishable key.
-- Add Supabase Auth and replace these policies before using real store data.
alter table public.supplier enable row level security;
alter table public.produk enable row level security;
alter table public.transaksi enable row level security;
alter table public.detail_transaksi enable row level security;

create policy "demo access supplier" on public.supplier
    for all to anon, authenticated using (true) with check (true);
create policy "demo access produk" on public.produk
    for all to anon, authenticated using (true) with check (true);
create policy "demo access transaksi" on public.transaksi
    for all to anon, authenticated using (true) with check (true);
create policy "demo access detail transaksi" on public.detail_transaksi
    for all to anon, authenticated using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on
    public.supplier,
    public.produk,
    public.transaksi,
    public.detail_transaksi
to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant select on public.view_laporan_transaksi, public.view_nilai_persediaan
to anon, authenticated;
grant execute on function public.proses_transaksi(text, bigint, text, jsonb)
to anon, authenticated;
